### PR TITLE
Rme output refactor

### PR DESCRIPTION
**Pull request by KellyMWhitehead**
@jtgilbert , @philipbaileynar 

Please review the changes. Thanks!

### CODE REVIEW

**Review by philipbaileynar — COMMENTED** [review]
@KellyMWhitehead I don't see the database indexes?

**Comment by KellyMWhitehead** [comment]
> @KellyMWhitehead I don't see the database indexes?

https://github.com/Riverscapes/riverscapes-tools/blob/8a35b2f8935c6d6698b57b8ad63678cd742702a0/packages/rme/rme/metric_engine.py#L1679-L1680

Are these correct? Also, should I have them combined, or on each column individually?

**Comment by philipbaileynar** [comment]
This is what I think the indexes should be:

```python
curs.execute('CREATE INDEX idx_dgo_fcode ON rme_dgos(FCode);')
curs.execute('CREATE INDEX idx_igo_fcode ON rme_igos(FCode);')
curs.execute('CREATE INDEX idx_dgos_level_path_seg_distance ON rme_dgos (level_path, seg_distance);')
curs.execute('CREATE INDEX idx_igos_level_path_seg_distance ON rme_igos (level_path, seg_distance);')
```

Thoughts?

**Comment by KellyMWhitehead** [comment]
> This is what I think the indexes should be:
> 
> ```python
> curs.execute('CREATE INDEX idx_dgo_fcode ON rme_dgos(FCode);')
> curs.execute('CREATE INDEX idx_igo_fcode ON rme_igos(FCode);')
> curs.execute('CREATE INDEX idx_dgos_level_path_seg_distance ON rme_dgos (level_path, seg_distance);')
> curs.execute('CREATE INDEX idx_igos_level_path_seg_distance ON rme_igos (level_path, seg_distance);')
> ```
> 
> Thoughts?

Sounds good. I will make the changes.

**Review by philipbaileynar — APPROVED** [review]
Indexes look good.

**Pull request merged**
