### PR TITLE
MHFD BRAT hydro params

### PR DESCRIPTION
**Pull request by jtgilbert**
updates to CO MHFD HUCs from @Jdgilby

### CODE REVIEW

**Review by philipbaileynar — APPROVED** [review]
Just BRAT params.

**Review by philipbaileynar — APPROVED** [review]
Looks good. Only BRAT params.

**Review by joewheaton — COMMENTED** [review]
Nice @jtgilbert, is this something you're showing @Jdgilby how to do as well?

**Comment by jtgilbert** [comment]
@joewheaton yeah, he's the one that updated the parameters, I just run the script to merge it into github since I have the credentials.

**Review by MattReimer — APPROVED** [review]

**Pull request merged**
