### PR TITLE
1st set of documentation pages

### PR DESCRIPTION
**Pull request by lauren-herbine**
5 stubbed out pages to see if things are working. Many don't have full content.

### CODE REVIEW

**Review by MattReimer — CHANGES_REQUESTED** [review]
Hey @lauren-herbine just a few changes here to make. 

1. You need `frontmatter` for this to work properly

```
---
title: MY TITLE HERE
---

My content here
```

2. (actually it's related to 1) Don't use the single `#` in the body. Move that title into the frontmatter and use ##, ###, #### where necessary in the body. 

Let me know if you have questions about this.

**Comment by lauren-herbine** [comment]
Hi @MattReimer - thanks for the feedback! Is this more like what you're looking for?

```
---
title: Stream Gradient
---
```

Stream gradient describes an increase or decrease in the elevation of the stream channel over a longitudinal distance.

image

*From Earth Communications, Chapter 4: Earth Surfaces, Section 4: High Gradient Streams*

### Why is this metric important?

* Helps predict debris flow transport and deposition (Fannin, R.J. and Rollerson, T.P., 1993),
* Helps to estimate distribution of aquatic organisms (Hicks, Brendan, J., and Hall, J.D., 2003), 
* Is a predictor of channel morphology

### Metric info:

**Machine Code:** STRMGRAD


.... etc.

**Comment by MattReimer** [comment]
> Hi @MattReimer - thanks for the feedback! Is this more like what you're looking for?

Almost.  The headings are hierarchical so it makes more sense for "### Why is this metric important?" and "### Metric info:" to use "##" instead of "###"


Like so 

```
---
title: this is the title and it is assumed to get H1 (so think #)
---

## this is subheading 1 on the page

### this is sub-subheading 1 on the page and it belongs to subheading 1

```

Sorry, there is technically nothing wrong with your example. I'm just being picky about semantics. I tend to do that sometimes.

**Comment by lauren-herbine** [comment]
Ok, gotcha, thanks!

**Comment by lauren-herbine** [comment]
@MattReimer I think all of the things we discussed should be fixed by now!

**Review by MattReimer — CHANGES_REQUESTED** [review]
Almost but not quite. the backticks shouldn't be there. 

```
---
title: MY TITLE HERE
---

My content here

```

Sorry this is confusing because i need to use backticks to write this comment in markdown.... it's a bit recursive. 

THe front matter is just "---" then a new line with "title: my title or whatever" then another line with "---"

**Comment by lauren-herbine** [comment]
Oh darn! Ok, haha, fixing now

**Review by MattReimer — APPROVED** [review]

**Comment by MattReimer** [comment]
Looks great. THis is merged and should be live now

**Comment by joewheaton** [comment]
@lauren-herbine, when you put up that "this is done" please also provide link. i.e. 

Also, @lauren-herbine and @shelbysawyer please see all the extensive (feel free to update) documentation here: https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/ and subpages. For example, the above stuff is clearly laid out here: https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/writing_content.html. Lets avoid having @MattReimer need to see these. Feel free to loop me on review requests for documentation so we can limit @MattReimer to just approving the pull requests making sure they are not breaking any thing.

**Pull request merged**
