### PR TITLE
Updated VegetationTypes.csv

### PR DESCRIPTION
**Pull request by Cashe93**
Updated VegetationTypes.csv with suitability codes used by MT Heritage.

@philipbaileynar it sounds like we will want to run sqlBRAT with these updated values. Is this correct @wally-mac?

### CODE REVIEW

**Comment by wally-mac** [comment]
@Cashe93 @philipbaileynar 
Yes, Joe and I had a discussion about it and we determined that we wanted to run it with the same vegetation codes as￼ was used by the  Montana Natural Heritage Program.

**Review by philipbaileynar — CHANGES_REQUESTED** [review]
@Cashe93 I am going to reject this CSV.

Please can you go back to the dev branch and start again. This time, please do not re-order the rows in the file. Use search to find specific veg types. 

The only changes you should make are changing the veg suitability integers.

**Comment by Cashe93** [comment]
Ill have to do this tomorrow.

**Comment by Cashe93** [comment]
@philipbaileynar, I've reordered the .csv to match the original document. Is there any other reason this wouldn't work?

**Comment by philipbaileynar** [comment]
@Cashe93 I won't be at a computer for another 5 hours. I will look then.

**Comment by Cashe93** [comment]
No worries, @philipbaileynar. If further changes need to be made please assign to @leallysmith or @Tanmanfalcon.

**Comment by philipbaileynar** [comment]
@Cashe93 this looks good! Now I just see suitabilities have changed. Names and all other information remain unchanged. This is much easier and cleaner to track.

So now we can run sqlBRAT on the pull request branch and it will use the MNHP vegetation suitabilities (while leaving the master branch with the original ET AL lab values).

@wally-mac and @joewheaton we have currently taken the quick-and-dirty route of updating the one default veg suitabilities list with the MNHP suitabilities. We have a few options on how to proceed long term:

1. Treat the MNHP suitabilities as the definitive values for all HUCs in North America (while still allowing each HUC to override them). i.e. merge this pull request and make the MNHP values the defaults for all BRAT runs everywhere.
2. Apply the MNHP veg suitabilities to all HUCs that were part of the MNHP run. This would keep the default BRAT suitabilities that ET AL Lab have established, but override them for MT, ND and SD with the MNHP values.
3. Just let the MNHP values hang out on a branch and remember to always run Montana BRAT using this branch.

**Comment by wally-mac** [comment]
@philipbaileynar Thanks for your work on this. It seems like option 2 is the best option for now.

**Comment by wally-mac** [comment]
@Cashe93 @philipbaileynar yes use the updated values.

**Comment by wally-mac** [comment]
Please disregard my comment.

**Pull request closed without merging**
