### PR TITLE
Initial documentation and report cards in prep for webinar

### LINKED ISSUE #493: Basic tool documentation for ChannelArea
Just get a first cut:

- [ ] Explanatory text and figure on landing page
- [ ] Outputs - Basic video for now
- [ ] Inputs & Intermediates - Basic video for new
- [ ] Report Card

### LINKED ISSUE #494: Basic tool documentation for RS_Context
Just get a first cut:

- [ ] Explanatory text and figure on landing page
- [ ] Outputs - Basic video for now
- [ ] Inputs & Intermediates - Basic video for new
- [ ] Report Card

### LINKED ISSUE #495: Basic tool documentation for TauDEM
Just get a first cut:

- [ ] Explanatory text and figure on landing page
- [ ] Outputs - Basic video for now
- [ ] Inputs & Intermediates - Basic video for new
- [ ] Report Card

### LINKED ISSUE #496: Basic tool documentation for VBET
Just get a first cut:

- [ ] Explanatory text and figure on landing page
- [ ] Outputs - Basic video for now
- [ ] Inputs & Intermediates - Basic video for new
- [ ] Report Card

### PR DESCRIPTION
**Pull request by jtgilbert**
closes #496 
closes #495 
closes #494
closes #493

### CODE REVIEW

**Comment by jtgilbert** [comment]
I'm available to make any changes you want to see today before the webinar tomorrow.

**Review by joewheaton — APPROVED** [review]
As the directory for report cards will have multiple versions in it through time, we should make sure filename reflects version.

**Comment by joewheaton** [comment]
@MattReimer I'm not sure if you want me approving these pull requests from @jtgilbert on markdown documentation? I can, but just thought I'd double check.

**Review by MattReimer — APPROVED** [review]

**Comment by joewheaton** [comment]
Thanks @MattReimer

**Pull request merged**
