### PR TITLE
started on brat documentation for 11/10 webinar

### PR DESCRIPTION
**Pull request by jtgilbert**

### CODE REVIEW

**Review by joewheaton — CHANGES_REQUESTED** [review]
Looks like a good start and improvement on all the edited and new files. Please do not delete the files that @philipbaileynar authored under Techncial_References. Please leave those as is for now (we can move later). I'd rather have some stuff up there than nothing. Once that is restored, I will approve and merge.

**Review by joewheaton — APPROVED** [review]
Looks better.

**Comment by MattReimer** [comment]
Hey @joewheaton remember to delete branches after merging. That way they don't build up in the system

**Comment by joewheaton** [comment]
Oops. Thanks for reminder. Will do.

**Pull request merged**
