### PR TITLE
updated some great plains overrides

### PR DESCRIPTION
**Pull request by jtgilbert**
herbaceous riparian is 4, overestimating capacity in prairie rivers.

### CODE REVIEW

**Comment by joewheaton** [comment]
So does this mean we should re-run all those Prarie runs? If so, that's fine, but what is plan of attack @jtgilbert? Also, what did MNH use for their BRAT run?

**Comment by jtgilbert** [comment]
@joewheaton I'm not sure what MNH used, but it must have been adjusted (not 4) because their runs are showing less capacity. I'll have to look at how widespread that class is in the region, but it's the main issue in Pumpkin Creek which is how I noticed it.

**Review by philipbaileynar — APPROVED** [review]
Looks good! 

Only includes data changes and they look reasonable.

**Comment by jtgilbert** [comment]
UPDATE: there was also a low flow equation issue.

**Pull request merged**
