### PR TITLE
Reports and Geopackages

### LINKED ISSUE #109: Convert VBET to GeoPackage
Please convert the VBET intermediates and outputs to GeoPackages to support the production of metrics and HTML report.

### PR DESCRIPTION
**Pull request by MattReimer**
This is a big one:

It closes #112 and closes #109 but it implements quite a bit more too in order to pave the way for widespread Geopackage use and the way we intend to use it in BRAT (eventually)

### What's in

* Reports for every tool. Some are fairly rudimentary but they are all there, waiting to be expanded.
* Geopackage support for all our `shapefile.py` methods
* Confinement switched to the new methods
* VBET Now writes Geopackages. Shapefiles remain in the outputs until BRAT no longer needs them
* Geopackage OR Shapefile support as inputs to Confinement tool
* All affected versions bumped

### What's not in

* RSContext has a report but no Geopackages
* BRAT Geopackage support (coming soon though)
* RVD Geopackages

Documentation for the new `GeopackageLayer` and `ShapefileLayer` classes is coming but not included in this

### Testing

All tools were run and the layers were checked manually. We should be in pretty good shape here.

### CODE REVIEW

**Comment by joewheaton** [comment]
Nice work @MattReimer and @philipbaileynar. These are exciting additions. I'd like to start poking around and taking a look. Should I dump all my downloaded Riverscape Projects, and are there any I should be testing or checking specifically from data.riverscapes.xyz for looking at reports and such?

**Comment by MattReimer** [comment]
Hey @joewheaton. There's nothing to see yet. I've upgraded the engines but I haven't churned out any projects so just hold on to whatever you have for now. 

The way we deploy engine changes and how the warehouse reflects them is  a conversation I'm eager to have but for now you'll only see the changes in any riverscapes-tools projects created after today.

**Comment by philipbaileynar** [comment]
@MattReimer let's make sure we version bump all tools once they go gpkg

Also I will need to coordinate a rave release that will not be backward compatible with prior versions. Maybe not a big deal as confinement and rvd are both new and vbet is under utilized to date.

**Comment by MattReimer** [comment]
@philipbaileynar all versions are bumped already as per a663d20

**Pull request merged**
