### PR TITLE
added missing max da values for mt

### PR DESCRIPTION
**Pull request by jtgilbert**
A few HUCs for MT were missing max DA values.

### CODE REVIEW

**Comment by jtgilbert** [comment]
Just bringing this up on your radar @MattReimer

**Review by philipbaileynar — APPROVED** [review]
Looks good. Only Max drainage has changed.

**Review by MattReimer — APPROVED** [review]

**Comment by MattReimer** [comment]
@jtgilbert this pull request conflics with another branch that got merged after you created it.

```
<<<<<<< HEAD
10030202,Cut Bank,3110.14,MT,(10**-3.16)*(DRNAREA**1.037)*(PRECIP**1.618) ,0.025*(DRNAREA**0.949)*(PRECIP**1.71),,42,,
=======
10030202,Cut Bank,3110.14,MT,(10**-3.16)*(DRNAREA**1.037)*(PRECIP**1.618) ,0.025*(DRNAREA**0.949)*(PRECIP**1.71),1250.0,42,,
>>>>>>> 0c6b747 (added missing max da values for mt)
```

and 

```
<<<<<<< HEAD
10050002,Upper Milk,5880.66,CN_MT,(0.0563*DRNAREA),0.034*(DRNAREA**0.447)*(PRECIP**2.39),,42,,
=======
10050002,Upper Milk,5880.66,CN_MT,(0.0563*DRNAREA),0.034*(DRNAREA**0.447)*(PRECIP**2.39),1500.0,42,,
>>>>>>> 0c6b747 (added missing max da values for mt)
```

Can you rebase on origin/master and resolve the conflicts please? Then we can merge.

**Comment by jtgilbert** [comment]
@MattReimer alright, I think it's rebased, unless I didn't do it right...

**Review by MattReimer — CHANGES_REQUESTED** [review]
Hey @jtgilbert looks like you ended up with unmerged text in your CSV files. We should handle this before we merge. Let me know if you need help. I'm around to day and I don' think it'll take long.

**Comment by jtgilbert** [comment]
@MattReimer yeah I need to review some of those git functions I haven't used for a minute. I cleaned up the csv.

**Review by MattReimer — APPROVED** [review]

**Comment by MattReimer** [comment]
Hey @jtgilbert sorry for all the trouble on one little CSV file but the fix for the fix created a merge problem in the branch

Screen Shot 2021-12-21 at 9 11 45 AM

I took the liberty of squashing and rebasing all this into one commit and I'll merge this change now.

**Pull request merged**
